package customerimporter

import (
	"testing"
)

func TestGetDomainNameFromRow(t *testing.T) {
	tt := []struct {
		name          string
		row           []string
		emailColIndex int
		expected      string
	}{
		{name: "extract domain name from row", row: []string{"Mildred", "Hernandez", "mhernandez0@github.io", "Female", "38.194.51.128"}, emailColIndex: 2, expected: "github.io"},
		{name: "extract lowercase domain name from row", row: []string{"Mildred", "Hernandez", "mhernandez0@GitHub.Io", "Female", "38.194.51.128"}, emailColIndex: 2, expected: "github.io"},
		{name: "return empty string for malformed input", row: []string{"Mildred", "Hernandez", "mhernandez0GitHub.Io", "Female", "38.194.51.128"}, emailColIndex: 2, expected: ""},
		{name: "handle empty string", row: []string{"Mildred", "Hernandez", "", "Female", "38.194.51.128"}, emailColIndex: 2, expected: ""},
		{name: "handle index out of bounds", row: []string{"mhernandez0@github.io"}, emailColIndex: 4, expected: ""},
		{name: "handle negative index", row: []string{"Mildred", "Hernandez", "mhernandez0@github.io", "Female", "38.194.51.128"}, emailColIndex: -4, expected: ""},
	}

	for _, tc := range tt {
		t.Run(tc.name, func(t *testing.T) {
			given := getDomainFromRow(tc.row, tc.emailColIndex)
			if given != tc.expected {
				t.Errorf("%s: expected: %s, got: %s\n", tc.name, tc.expected, given)
			}
		})
	}
}

func TestGetDomainCounts(t *testing.T) {
	tt := []struct {
		name        string
		filepath    string
		expected    []*Domain
		shouldError bool
	}{
		{name: "expect customers to be parsed and sorted", filepath: "./customers.csv", expected: expectedSortedDomains, shouldError: false},
		{name: "expect empty slice when empty list", filepath: "./empty_list.csv", expected: []*Domain{}, shouldError: false},
		{name: "expect error when empty file", filepath: "./empty_file.csv", expected: nil, shouldError: true},
		{name: "expect error when file not found", filepath: "./unknown.csv", expected: nil, shouldError: true},
	}

	for _, tc := range tt {
		t.Run(tc.name, func(t *testing.T) {
			given, err := GetDomainCounts(tc.filepath)
			if tc.shouldError {
				if err == nil {
					t.Errorf("%s: expected error, got nil\n", tc.name)
				}
			} else {
				if err != nil {
					t.Fatalf("%s: error: %+v\n", tc.name, err)
				}
				if len(given) != len(tc.expected) {
					t.Errorf("%s: expected length: %d, got: %d\n", tc.name, len(tc.expected), len(given))
				}

				for i, d := range given {
					expectedDomian := tc.expected[i].Name
					expectedCount := tc.expected[i].Count
					if d.Name != expectedDomian || d.Count != expectedCount {
						t.Fatalf("%s: expected: [%s]: %d, got: [%s]: %d\n", tc.name, expectedDomian, expectedCount, d.Name, d.Count)
					}
				}
			}
		})
	}
}

var expectedSortedDomains = []*Domain{
	{Name: "123-reg.co.uk", Count: 8},
	{Name: "163.com", Count: 6},
	{Name: "1688.com", Count: 3},
	{Name: "1und1.de", Count: 5},
	{Name: "360.cn", Count: 6},
	{Name: "4shared.com", Count: 5},
	{Name: "51.la", Count: 4},
	{Name: "a8.net", Count: 6},
	{Name: "abc.net.au", Count: 7},
	{Name: "about.com", Count: 5},
	{Name: "about.me", Count: 2},
	{Name: "aboutads.info", Count: 2},
	{Name: "accuweather.com", Count: 6},
	{Name: "acquirethisname.com", Count: 6},
	{Name: "addthis.com", Count: 10},
	{Name: "addtoany.com", Count: 6},
	{Name: "admin.ch", Count: 9},
	{Name: "adobe.com", Count: 6},
	{Name: "alexa.com", Count: 6},
	{Name: "alibaba.com", Count: 7},
	{Name: "altervista.org", Count: 7},
	{Name: "amazon.co.jp", Count: 5},
	{Name: "amazon.co.uk", Count: 3},
	{Name: "amazon.com", Count: 6},
	{Name: "amazon.de", Count: 7},
	{Name: "amazonaws.com", Count: 6},
	{Name: "ameblo.jp", Count: 6},
	{Name: "angelfire.com", Count: 5},
	{Name: "answers.com", Count: 5},
	{Name: "aol.com", Count: 5},
	{Name: "apache.org", Count: 2},
	{Name: "apple.com", Count: 5},
	{Name: "archive.org", Count: 7},
	{Name: "arizona.edu", Count: 5},
	{Name: "army.mil", Count: 8},
	{Name: "arstechnica.com", Count: 9},
	{Name: "artisteer.com", Count: 5},
	{Name: "ask.com", Count: 6},
	{Name: "auda.org.au", Count: 5},
	{Name: "baidu.com", Count: 7},
	{Name: "bandcamp.com", Count: 3},
	{Name: "barnesandnoble.com", Count: 8},
	{Name: "bbb.org", Count: 5},
	{Name: "bbc.co.uk", Count: 10},
	{Name: "behance.net", Count: 10},
	{Name: "berkeley.edu", Count: 7},
	{Name: "biblegateway.com", Count: 6},
	{Name: "bigcartel.com", Count: 2},
	{Name: "biglobe.ne.jp", Count: 4},
	{Name: "bing.com", Count: 4},
	{Name: "bizjournals.com", Count: 2},
	{Name: "blinklist.com", Count: 7},
	{Name: "blog.com", Count: 6},
	{Name: "blogger.com", Count: 8},
	{Name: "bloglines.com", Count: 6},
	{Name: "bloglovin.com", Count: 7},
	{Name: "blogs.com", Count: 4},
	{Name: "blogspot.com", Count: 6},
	{Name: "blogtalkradio.com", Count: 7},
	{Name: "bloomberg.com", Count: 9},
	{Name: "bluehost.com", Count: 5},
	{Name: "booking.com", Count: 4},
	{Name: "boston.com", Count: 4},
	{Name: "bravesites.com", Count: 5},
	{Name: "businessinsider.com", Count: 5},
	{Name: "businessweek.com", Count: 3},
	{Name: "businesswire.com", Count: 2},
	{Name: "buzzfeed.com", Count: 10},
	{Name: "ca.gov", Count: 9},
	{Name: "cafepress.com", Count: 6},
	{Name: "cam.ac.uk", Count: 5},
	{Name: "canalblog.com", Count: 7},
	{Name: "cargocollective.com", Count: 6},
	{Name: "cbc.ca", Count: 7},
	{Name: "cbslocal.com", Count: 8},
	{Name: "cbsnews.com", Count: 8},
	{Name: "cdbaby.com", Count: 4},
	{Name: "cdc.gov", Count: 6},
	{Name: "census.gov", Count: 7},
	{Name: "chicagotribune.com", Count: 7},
	{Name: "china.com.cn", Count: 5},
	{Name: "chron.com", Count: 6},
	{Name: "chronoengine.com", Count: 7},
	{Name: "cisco.com", Count: 11},
	{Name: "clickbank.net", Count: 5},
	{Name: "cloudflare.com", Count: 3},
	{Name: "cmu.edu", Count: 4},
	{Name: "cnbc.com", Count: 6},
	{Name: "cnet.com", Count: 6},
	{Name: "cnn.com", Count: 4},
	{Name: "cocolog-nifty.com", Count: 7},
	{Name: "columbia.edu", Count: 4},
	{Name: "com.com", Count: 5},
	{Name: "comcast.net", Count: 3},
	{Name: "comsenz.com", Count: 7},
	{Name: "constantcontact.com", Count: 8},
	{Name: "cornell.edu", Count: 4},
	{Name: "cpanel.net", Count: 4},
	{Name: "craigslist.org", Count: 8},
	{Name: "creativecommons.org", Count: 5},
	{Name: "csmonitor.com", Count: 6},
	{Name: "cyberchimps.com", Count: 6},
	{Name: "dagondesign.com", Count: 10},
	{Name: "dailymail.co.uk", Count: 9},
	{Name: "dailymotion.com", Count: 1},
	{Name: "de.vu", Count: 4},
	{Name: "dedecms.com", Count: 4},
	{Name: "delicious.com", Count: 6},
	{Name: "deliciousdays.com", Count: 7},
	{Name: "dell.com", Count: 4},
	{Name: "desdev.cn", Count: 11},
	{Name: "devhub.com", Count: 6},
	{Name: "deviantart.com", Count: 7},
	{Name: "digg.com", Count: 2},
	{Name: "diigo.com", Count: 5},
	{Name: "dion.ne.jp", Count: 7},
	{Name: "discovery.com", Count: 5},
	{Name: "discuz.net", Count: 5},
	{Name: "disqus.com", Count: 6},
	{Name: "dmoz.org", Count: 5},
	{Name: "domainmarket.com", Count: 13},
	{Name: "dot.gov", Count: 4},
	{Name: "dropbox.com", Count: 5},
	{Name: "drupal.org", Count: 3},
	{Name: "dyndns.org", Count: 4},
	{Name: "e-recht24.de", Count: 7},
	{Name: "earthlink.net", Count: 9},
	{Name: "ebay.co.uk", Count: 5},
	{Name: "ebay.com", Count: 4},
	{Name: "economist.com", Count: 3},
	{Name: "ed.gov", Count: 3},
	{Name: "edublogs.org", Count: 8},
	{Name: "eepurl.com", Count: 7},
	{Name: "ehow.com", Count: 7},
	{Name: "elegantthemes.com", Count: 9},
	{Name: "elpais.com", Count: 10},
	{Name: "engadget.com", Count: 6},
	{Name: "epa.gov", Count: 8},
	{Name: "etsy.com", Count: 6},
	{Name: "europa.eu", Count: 2},
	{Name: "eventbrite.com", Count: 4},
	{Name: "examiner.com", Count: 5},
	{Name: "example.com", Count: 8},
	{Name: "exblog.jp", Count: 5},
	{Name: "ezinearticles.com", Count: 9},
	{Name: "facebook.com", Count: 7},
	{Name: "fastcompany.com", Count: 4},
	{Name: "fc2.com", Count: 6},
	{Name: "fda.gov", Count: 2},
	{Name: "feedburner.com", Count: 5},
	{Name: "fema.gov", Count: 5},
	{Name: "flavors.me", Count: 7},
	{Name: "flickr.com", Count: 5},
	{Name: "forbes.com", Count: 7},
	{Name: "fotki.com", Count: 5},
	{Name: "foxnews.com", Count: 5},
	{Name: "free.fr", Count: 8},
	{Name: "freewebs.com", Count: 10},
	{Name: "friendfeed.com", Count: 4},
	{Name: "ft.com", Count: 5},
	{Name: "ftc.gov", Count: 9},
	{Name: "furl.net", Count: 4},
	{Name: "g.co", Count: 6},
	{Name: "geocities.com", Count: 12},
	{Name: "geocities.jp", Count: 6},
	{Name: "github.com", Count: 7},
	{Name: "github.io", Count: 8},
	{Name: "gizmodo.com", Count: 5},
	{Name: "globo.com", Count: 10},
	{Name: "gmpg.org", Count: 5},
	{Name: "gnu.org", Count: 5},
	{Name: "go.com", Count: 11},
	{Name: "godaddy.com", Count: 5},
	{Name: "goo.gl", Count: 8},
	{Name: "goo.ne.jp", Count: 6},
	{Name: "goodreads.com", Count: 3},
	{Name: "google.ca", Count: 7},
	{Name: "google.cn", Count: 5},
	{Name: "google.co.jp", Count: 5},
	{Name: "google.co.uk", Count: 10},
	{Name: "google.com", Count: 9},
	{Name: "google.com.au", Count: 8},
	{Name: "google.com.br", Count: 5},
	{Name: "google.com.hk", Count: 5},
	{Name: "google.de", Count: 11},
	{Name: "google.es", Count: 9},
	{Name: "google.fr", Count: 12},
	{Name: "google.it", Count: 4},
	{Name: "google.nl", Count: 7},
	{Name: "google.pl", Count: 6},
	{Name: "google.ru", Count: 9},
	{Name: "gov.uk", Count: 4},
	{Name: "gravatar.com", Count: 4},
	{Name: "guardian.co.uk", Count: 8},
	{Name: "hao123.com", Count: 7},
	{Name: "harvard.edu", Count: 8},
	{Name: "hatena.ne.jp", Count: 4},
	{Name: "hc360.com", Count: 5},
	{Name: "hexun.com", Count: 8},
	{Name: "hhs.gov", Count: 5},
	{Name: "hibu.com", Count: 10},
	{Name: "histats.com", Count: 5},
	{Name: "home.pl", Count: 3},
	{Name: "homestead.com", Count: 2},
	{Name: "hostgator.com", Count: 9},
	{Name: "house.gov", Count: 5},
	{Name: "howstuffworks.com", Count: 5},
	{Name: "hp.com", Count: 4},
	{Name: "hubpages.com", Count: 9},
	{Name: "hud.gov", Count: 6},
	{Name: "huffingtonpost.com", Count: 10},
	{Name: "hugedomains.com", Count: 6},
	{Name: "i2i.jp", Count: 9},
	{Name: "ibm.com", Count: 5},
	{Name: "icio.us", Count: 3},
	{Name: "icq.com", Count: 8},
	{Name: "ifeng.com", Count: 9},
	{Name: "ihg.com", Count: 9},
	{Name: "illinois.edu", Count: 6},
	{Name: "imageshack.us", Count: 8},
	{Name: "imdb.com", Count: 2},
	{Name: "imgur.com", Count: 2},
	{Name: "independent.co.uk", Count: 11},
	{Name: "indiatimes.com", Count: 5},
	{Name: "indiegogo.com", Count: 8},
	{Name: "infoseek.co.jp", Count: 4},
	{Name: "instagram.com", Count: 6},
	{Name: "intel.com", Count: 4},
	{Name: "irs.gov", Count: 9},
	{Name: "is.gd", Count: 5},
	{Name: "issuu.com", Count: 7},
	{Name: "istockphoto.com", Count: 2},
	{Name: "jalbum.net", Count: 2},
	{Name: "japanpost.jp", Count: 5},
	{Name: "java.com", Count: 2},
	{Name: "jiathis.com", Count: 10},
	{Name: "jigsy.com", Count: 2},
	{Name: "jimdo.com", Count: 5},
	{Name: "joomla.org", Count: 2},
	{Name: "jugem.jp", Count: 5},
	{Name: "kickstarter.com", Count: 10},
	{Name: "last.fm", Count: 6},
	{Name: "latimes.com", Count: 2},
	{Name: "linkedin.com", Count: 2},
	{Name: "list-manage.com", Count: 3},
	{Name: "live.com", Count: 7},
	{Name: "liveinternet.ru", Count: 7},
	{Name: "livejournal.com", Count: 8},
	{Name: "loc.gov", Count: 14},
	{Name: "lulu.com", Count: 7},
	{Name: "lycos.com", Count: 6},
	{Name: "mac.com", Count: 7},
	{Name: "macromedia.com", Count: 7},
	{Name: "mail.ru", Count: 5},
	{Name: "mapquest.com", Count: 5},
	{Name: "mapy.cz", Count: 5},
	{Name: "marketwatch.com", Count: 7},
	{Name: "marriott.com", Count: 6},
	{Name: "mashable.com", Count: 5},
	{Name: "mayoclinic.com", Count: 5},
	{Name: "mediafire.com", Count: 4},
	{Name: "meetup.com", Count: 4},
	{Name: "merriam-webster.com", Count: 6},
	{Name: "microsoft.com", Count: 7},
	{Name: "miibeian.gov.cn", Count: 4},
	{Name: "miitbeian.gov.cn", Count: 12},
	{Name: "mit.edu", Count: 9},
	{Name: "mlb.com", Count: 7},
	{Name: "moonfruit.com", Count: 6},
	{Name: "mozilla.com", Count: 7},
	{Name: "mozilla.org", Count: 2},
	{Name: "msn.com", Count: 6},
	{Name: "msu.edu", Count: 3},
	{Name: "mtv.com", Count: 6},
	{Name: "multiply.com", Count: 5},
	{Name: "myspace.com", Count: 8},
	{Name: "mysql.com", Count: 6},
	{Name: "narod.ru", Count: 2},
	{Name: "nasa.gov", Count: 8},
	{Name: "nationalgeographic.com", Count: 6},
	{Name: "nature.com", Count: 7},
	{Name: "naver.com", Count: 5},
	{Name: "nba.com", Count: 5},
	{Name: "nbcnews.com", Count: 5},
	{Name: "netlog.com", Count: 8},
	{Name: "netscape.com", Count: 4},
	{Name: "netvibes.com", Count: 8},
	{Name: "networkadvertising.org", Count: 11},
	{Name: "networksolutions.com", Count: 3},
	{Name: "newsvine.com", Count: 8},
	{Name: "newyorker.com", Count: 3},
	{Name: "nhs.uk", Count: 9},
	{Name: "nifty.com", Count: 9},
	{Name: "nih.gov", Count: 6},
	{Name: "ning.com", Count: 1},
	{Name: "noaa.gov", Count: 6},
	{Name: "npr.org", Count: 3},
	{Name: "nps.gov", Count: 3},
	{Name: "nsw.gov.au", Count: 6},
	{Name: "nydailynews.com", Count: 7},
	{Name: "nymag.com", Count: 11},
	{Name: "nytimes.com", Count: 3},
	{Name: "nyu.edu", Count: 4},
	{Name: "oaic.gov.au", Count: 6},
	{Name: "oakley.com", Count: 9},
	{Name: "ocn.ne.jp", Count: 4},
	{Name: "odnoklassniki.ru", Count: 6},
	{Name: "omniture.com", Count: 5},
	{Name: "opensource.org", Count: 5},
	{Name: "opera.com", Count: 10},
	{Name: "oracle.com", Count: 5},
	{Name: "over-blog.com", Count: 6},
	{Name: "ovh.net", Count: 9},
	{Name: "ow.ly", Count: 6},
	{Name: "ox.ac.uk", Count: 3},
	{Name: "pagesperso-orange.fr", Count: 4},
	{Name: "paginegialle.it", Count: 6},
	{Name: "parallels.com", Count: 6},
	{Name: "patch.com", Count: 8},
	{Name: "paypal.com", Count: 5},
	{Name: "pbs.org", Count: 6},
	{Name: "pcworld.com", Count: 4},
	{Name: "pen.io", Count: 4},
	{Name: "people.com.cn", Count: 4},
	{Name: "phoca.cz", Count: 6},
	{Name: "photobucket.com", Count: 9},
	{Name: "php.net", Count: 2},
	{Name: "phpbb.com", Count: 6},
	{Name: "pinterest.com", Count: 7},
	{Name: "plala.or.jp", Count: 4},
	{Name: "posterous.com", Count: 3},
	{Name: "princeton.edu", Count: 6},
	{Name: "printfriendly.com", Count: 6},
	{Name: "privacy.gov.au", Count: 4},
	{Name: "prlog.org", Count: 6},
	{Name: "prnewswire.com", Count: 7},
	{Name: "prweb.com", Count: 8},
	{Name: "psu.edu", Count: 6},
	{Name: "purevolume.com", Count: 8},
	{Name: "qq.com", Count: 5},
	{Name: "quantcast.com", Count: 3},
	{Name: "rakuten.co.jp", Count: 8},
	{Name: "rambler.ru", Count: 10},
	{Name: "redcross.org", Count: 5},
	{Name: "reddit.com", Count: 13},
	{Name: "rediff.com", Count: 9},
	{Name: "reference.com", Count: 4},
	{Name: "reuters.com", Count: 6},
	{Name: "reverbnation.com", Count: 6},
	{Name: "sakura.ne.jp", Count: 7},
	{Name: "salon.com", Count: 5},
	{Name: "samsung.com", Count: 5},
	{Name: "sbwire.com", Count: 6},
	{Name: "sciencedaily.com", Count: 5},
	{Name: "sciencedirect.com", Count: 4},
	{Name: "scientificamerican.com", Count: 4},
	{Name: "scribd.com", Count: 5},
	{Name: "seattletimes.com", Count: 10},
	{Name: "seesaa.net", Count: 5},
	{Name: "senate.gov", Count: 5},
	{Name: "sfgate.com", Count: 10},
	{Name: "shareasale.com", Count: 6},
	{Name: "shinystat.com", Count: 10},
	{Name: "shop-pro.jp", Count: 3},
	{Name: "shutterfly.com", Count: 6},
	{Name: "si.edu", Count: 6},
	{Name: "simplemachines.org", Count: 4},
	{Name: "sina.com.cn", Count: 9},
	{Name: "sitemeter.com", Count: 6},
	{Name: "skype.com", Count: 8},
	{Name: "skyrock.com", Count: 7},
	{Name: "slashdot.org", Count: 8},
	{Name: "slate.com", Count: 4},
	{Name: "slideshare.net", Count: 9},
	{Name: "smh.com.au", Count: 8},
	{Name: "smugmug.com", Count: 8},
	{Name: "so-net.ne.jp", Count: 7},
	{Name: "sogou.com", Count: 7},
	{Name: "sohu.com", Count: 4},
	{Name: "soundcloud.com", Count: 3},
	{Name: "soup.io", Count: 4},
	{Name: "sourceforge.net", Count: 7},
	{Name: "sphinn.com", Count: 9},
	{Name: "spiegel.de", Count: 2},
	{Name: "spotify.com", Count: 5},
	{Name: "springer.com", Count: 5},
	{Name: "squarespace.com", Count: 10},
	{Name: "squidoo.com", Count: 9},
	{Name: "stanford.edu", Count: 11},
	{Name: "statcounter.com", Count: 6},
	{Name: "state.gov", Count: 3},
	{Name: "state.tx.us", Count: 4},
	{Name: "storify.com", Count: 8},
	{Name: "studiopress.com", Count: 12},
	{Name: "stumbleupon.com", Count: 7},
	{Name: "sun.com", Count: 10},
	{Name: "surveymonkey.com", Count: 5},
	{Name: "symantec.com", Count: 8},
	{Name: "t-online.de", Count: 9},
	{Name: "t.co", Count: 3},
	{Name: "tamu.edu", Count: 8},
	{Name: "taobao.com", Count: 7},
	{Name: "techcrunch.com", Count: 4},
	{Name: "technorati.com", Count: 3},
	{Name: "ted.com", Count: 1},
	{Name: "telegraph.co.uk", Count: 7},
	{Name: "theatlantic.com", Count: 5},
	{Name: "theglobeandmail.com", Count: 5},
	{Name: "theguardian.com", Count: 3},
	{Name: "themeforest.net", Count: 2},
	{Name: "thetimes.co.uk", Count: 4},
	{Name: "time.com", Count: 8},
	{Name: "timesonline.co.uk", Count: 5},
	{Name: "tiny.cc", Count: 9},
	{Name: "tinypic.com", Count: 6},
	{Name: "tinyurl.com", Count: 9},
	{Name: "tmall.com", Count: 6},
	{Name: "toplist.cz", Count: 6},
	{Name: "topsy.com", Count: 4},
	{Name: "trellian.com", Count: 2},
	{Name: "tripadvisor.com", Count: 6},
	{Name: "tripod.com", Count: 7},
	{Name: "tumblr.com", Count: 7},
	{Name: "tuttocitta.it", Count: 7},
	{Name: "twitpic.com", Count: 8},
	{Name: "twitter.com", Count: 8},
	{Name: "typepad.com", Count: 8},
	{Name: "ucla.edu", Count: 7},
	{Name: "ucoz.com", Count: 5},
	{Name: "ucoz.ru", Count: 2},
	{Name: "ucsd.edu", Count: 8},
	{Name: "uiuc.edu", Count: 6},
	{Name: "umich.edu", Count: 6},
	{Name: "umn.edu", Count: 5},
	{Name: "un.org", Count: 1},
	{Name: "unblog.fr", Count: 8},
	{Name: "unc.edu", Count: 8},
	{Name: "unesco.org", Count: 7},
	{Name: "unicef.org", Count: 6},
	{Name: "uol.com.br", Count: 5},
	{Name: "upenn.edu", Count: 6},
	{Name: "usa.gov", Count: 4},
	{Name: "usatoday.com", Count: 7},
	{Name: "usda.gov", Count: 6},
	{Name: "usgs.gov", Count: 5},
	{Name: "usnews.com", Count: 8},
	{Name: "ustream.tv", Count: 4},
	{Name: "utexas.edu", Count: 5},
	{Name: "va.gov", Count: 3},
	{Name: "vimeo.com", Count: 3},
	{Name: "vinaora.com", Count: 5},
	{Name: "virginia.edu", Count: 5},
	{Name: "vistaprint.com", Count: 8},
	{Name: "vk.com", Count: 11},
	{Name: "vkontakte.ru", Count: 2},
	{Name: "w3.org", Count: 6},
	{Name: "walmart.com", Count: 7},
	{Name: "washington.edu", Count: 4},
	{Name: "washingtonpost.com", Count: 10},
	{Name: "weather.com", Count: 5},
	{Name: "webeden.co.uk", Count: 4},
	{Name: "webmd.com", Count: 5},
	{Name: "webnode.com", Count: 5},
	{Name: "webs.com", Count: 5},
	{Name: "weebly.com", Count: 12},
	{Name: "weibo.com", Count: 5},
	{Name: "whitehouse.gov", Count: 9},
	{Name: "who.int", Count: 3},
	{Name: "wikia.com", Count: 6},
	{Name: "wikimedia.org", Count: 6},
	{Name: "wikipedia.org", Count: 5},
	{Name: "wikispaces.com", Count: 4},
	{Name: "wiley.com", Count: 8},
	{Name: "wired.com", Count: 8},
	{Name: "wisc.edu", Count: 8},
	{Name: "wix.com", Count: 4},
	{Name: "woothemes.com", Count: 10},
	{Name: "wordpress.com", Count: 4},
	{Name: "wordpress.org", Count: 7},
	{Name: "wp.com", Count: 7},
	{Name: "wsj.com", Count: 5},
	{Name: "wufoo.com", Count: 2},
	{Name: "wunderground.com", Count: 3},
	{Name: "xing.com", Count: 9},
	{Name: "xinhuanet.com", Count: 6},
	{Name: "xrea.com", Count: 2},
	{Name: "yahoo.co.jp", Count: 5},
	{Name: "yahoo.com", Count: 7},
	{Name: "yale.edu", Count: 7},
	{Name: "yandex.ru", Count: 5},
	{Name: "ycombinator.com", Count: 6},
	{Name: "yellowbook.com", Count: 5},
	{Name: "yellowpages.com", Count: 7},
	{Name: "yelp.com", Count: 4},
	{Name: "yolasite.com", Count: 9},
	{Name: "youku.com", Count: 5},
	{Name: "youtu.be", Count: 6},
	{Name: "youtube.com", Count: 3},
	{Name: "zdnet.com", Count: 8},
	{Name: "zimbio.com", Count: 3},
}
